adds logic to publication channels selection
kanselarij-vlaanderen/frontend-persberichten pull request #24
Opened 2021-08-19 16:11 UTC by eduardtsatourov

2021-08-19 16:32 UTC, erikap requested changes

2021-08-19 16:32 UTC, erikap commented on app/config/constants.js
> +    SUBSCRIBERS_FLANDERS_BE: 'http://themis.vlaanderen.be/id/publicatiekanaal/c06c30f5-d9e9-490e-822c-43faa9d0b25e'
Hier is precies wat verwarring rond de verschillende publicatiekanalen. Er is:
- abonnees Vlaanderen.be (`SUBSCRIBERS_FLANDERS_BE`)
- website Vlaanderen.be (`WEBSITE_FLANDERS_BE`)

Het is `WEBSITE_FLANDERS_BE` dat automatisch toegevoegd moet worden als een van de 2 anderen geselecteerd wordt.

Voor de URIs: zie de [migration in de backend](https://github.com/kanselarij-vlaanderen/app-persberichten/blob/master/config/migrations/20210510100000-publication-channels.sparql#L14-L20)

2021-08-19 16:32 UTC, erikap commented on app/components/input-field/press-release-publication-channels.js
> +  @tracked subscribersFlandersBe;
Zie ook vorige comment. Ik denk dat je voor de duidelijkheid best spreekt over `websiteFlandersBe`

2021-08-19 16:32 UTC, erikap commented on app/components/input-field/press-release-publication-channels.js
> +  setDisableFlandersBeChannel(selectedChannels) {
Dit kan je omvormen naar een get-function `get isDisabledWebsiteFlandersBeChannel`. Dan heb je de `@tracked disableFlandersBeChannel` niet meer nodig.

2021-08-19 16:32 UTC, erikap commented on app/components/input-field/press-release-publication-channels.hbs
>        {{on "change" (fn this.getSelectedPublicationChannels publicationChannel)}}
Dit is gepasseerd in een vorige PR, maar `this.updateSelectedPublicationChannels` is misschien een duidelijkere naam voor de action?

2021-08-19 16:32 UTC, erikap commented on app/components/input-field/press-release-publication-channels.js
> +    if (selectedPublicationChannels.length && !selectedPublicationChannels.includes(this.subscribersFlandersBe)) {
Net voor deze `if` misschien een comment toevoegen zoals
```
// if any publication-channel is selected, website Flanders publication-channel must be automatically added
```
zodat we in de toekomst nog weten waarom we dit doen

2021-08-19 22:47 UTC, eduardtsatourov commented on app/components/input-field/press-release-publication-channels.js
> +  setDisableFlandersBeChannel(selectedChannels) {
thanks voor de tip :)

2021-08-20 06:52 UTC, erikap requested changes

2021-08-20 06:52 UTC, erikap commented on app/components/input-field/press-release-publication-channels.js
> +    const selectedPublicationChannels = this.args.publicationChannels.slice(0);
De `.slice(0)` lijkt mij hier niet nodig?

2021-08-20 06:52 UTC, erikap commented on app/components/input-field/press-release-publication-channels.js
> +    if (selectedPublicationChannels.length > 1 && selectedPublicationChannels.includes(this.websiteFlandersBe)) {
Je kan dit gewoon als `return` statement gebruiken ipv met if-else te werken

2021-08-20 09:45 UTC, erikap approved these changes

2021-08-20 09:45 UTC, merged