Feature/pers 133
kanselarij-vlaanderen/frontend-persberichten pull request #29
Opened 2021-08-28 16:10 UTC by eduardtsatourov

2021-08-29 15:39 UTC, erikap requested changes

2021-08-29 15:39 UTC, erikap commented on app/components/contact/contact-item-modal.js
> +  @tracked contact = {};
Ik zou deze component al laten werken met ember-data records i.p.v. een plain JS object. Hierdoor gaat deze modal later herbruikbaar zijn om ook contact-items te bewerken die reeds opgeslagen zijn.

Je kan, net zoals bij bronnen, voor ieder contact-item onmiddellijk een telephone en mail record aanmaken. Indien er niets ingevuld wordt in deze invulvelden, blijft het `value` attribuut hiervan gewoon leeg.

Het aanmaken/verwijderen/opslaan zou ik, zoals je nu gedaan hebt, buiten deze component houden zodat deze component als enige verantwoordelijkheid heeft dat de gegevens aangepast kunnen worden.

2021-08-29 15:39 UTC, erikap commented on app/components/contact/contact-item-modal.js
> +export default class ContactContactItemModalComponent extends Component {
Ik zou de componenten gerelateerd aan contact-items in een subfolder `contact-item` onder components zetten zodat ze gescheiden blijven van de `contact` components die voor bronnen gebruikt worden.

2021-08-29 15:39 UTC, erikap commented on app/controllers/contacts/new.js
> +    await this.model.save();
De mailing-list moet als eerste opgeslagen worden. Aangezien de relatie one-to-many is, gaat ember-data de relatie opslaan aan de one-side (dus aan de kant van contact-item) en niet aan de many-side. Als je eerst het contact-item opslaat gaat de link naar de mailing-list niet correct gelegd worden omdat die nog niet bestaat in de backend.

2021-08-29 15:39 UTC, erikap commented on app/controllers/contacts/new.js
> +    this.contacts.map(async contact => {
Wil je hier geen `await Promise.all()` doen van de promises die gereturned worden door de `map()`? Indien je met de return value van `map()` niets doet, is het duidelijker om `forEach` te gebruiken. Maar ik denk dat je hier de promises expliciet wilt awaiten voor je verder gaat.

2021-08-29 15:39 UTC, erikap commented on app/components/contact/contact-item-table.hbs
> +                Naam Contactpersoon
Geen hoofdletter voor contactpersoon

2021-08-29 15:39 UTC, erikap commented on app/templates/contacts/new.hbs
> +    @selectedContact={{this.selectedContact}}
`@selectedContact` is een beetje vreemd voor een modal die maar 1 contact toont. Gewoon `@contact` volstaat?

2021-08-29 15:39 UTC, erikap commented on app/controllers/contacts/new.js
> +  async saveContactList() {
Hier zou ik een `@task` van maken zodanig dat je een loading-state kan tonen op de button zolang de mailing list aangemaakt wordt.

2021-08-30 12:38 UTC, eduardtsatourov commented on app/controllers/contacts/new.js
> +    this.step = 0;
thanks for the tip

2021-08-31 09:21 UTC, erikap requested changes

2021-08-31 09:21 UTC, erikap commented on app/components/contact/contact-item/contact-item-modal.js
> +export default class ContactContactItemModalComponent extends Component {
Ik bedoelde hier een subfolder `contact-item` direct onder `components` en niet in `components/contact`. Zelfde voor de table component.

In lijn met de componenten onder `contact` en `press-release` zou ik die dan ook gewoon `modal.js` en `table.js` noemen.

2021-08-31 09:21 UTC, erikap commented on app/templates/contacts/new.hbs
> +      {{#if showContactItemModal}}
Scoping toevoegen

2021-08-31 09:21 UTC, erikap commented on app/components/contact/contact-item/contact-item-table.hbs
> +                    {{on "click" (fn @onOpenContactItem index)}}
Waarom werk je hier met de index en geef je niet gewoon het contact-object door?

2021-08-31 09:21 UTC, erikap commented on app/components/contact/contact-item/contact-item-modal.js
> +      this.contact = this.store.createRecord('contact-item', {telephone, mailAddress});
Het aanmaken van het nieuwe record zou ik buiten deze component houden en in de `openContactItemModal` action van de `new.js` controller doen. Op die manier wordt deze component eenvoudiger: hij krijgt in alle gevallen een contact binnen in `@contact`. De lokale `this.contact` lijkt me dan ook niet meer nodig.

2021-08-31 09:21 UTC, erikap commented on app/components/contact/contact-item/contact-item-modal.js
> +           !this.contact.organizationName;
De [`isPresent` of `isBlank`](https://api.emberjs.com/ember/release/functions/@ember%2Futils/isPresent) utils zijn hier geschikter om values met enkel whitespaces niet als `true` te aanzien.

2021-08-31 09:21 UTC, erikap commented on app/controllers/contacts/new.js
> +      return !this.model.name;
De [`isPresent` of `isBlank`](https://api.emberjs.com/ember/release/functions/@ember%2Futils/isPresent) utils zijn hier geschikter om values met enkel whitespaces niet als `true` te aanzien.

2021-08-31 09:21 UTC, erikap commented on app/controllers/contacts/new.js
> +    this.showContactItemModal = false;
Wil je in alle gevallen waar de modal gesloten wordt `this.selectedContact` niet op `null` zetten?
Als je dat hier doet, kan je deze methode aanroepen vanuit de andere acties zoals `addContact()`, `deleteContact()`, ...

2021-08-31 09:21 UTC, erikap commented on app/components/contact/contact-item/contact-item-modal.hbs
> +          {{on "click" (fn @onDeleteContact this.contact)}}
Je geeft hier `this.contact` mee als argument, maar gebruikt dat argument niet in de action.

2021-08-31 09:21 UTC, erikap commented on app/controllers/contacts/new.js
> +    this.contacts.addObject(contact);
Dit lijkt mij overbodig. Aangezien objects by reference doorgegeven worden, ben je hier hetzelfde object aan het verwijderen en opnieuw aan het toevoegen?

2021-08-31 10:49 UTC, erikap commented
Kijk je ook de linting issues nog eens na in deze branch?

2021-08-31 18:20 UTC, eduardtsatourov commented
in de laatste changes heb ik een bug ontdekt => bij het annuleren werd contact-item toch aangepast
 *hiervoor heb ik een kleine snapshot gemaakt in new.js om changes te kunnen reverten bij het annuleren van de modal
 *ik heb dit ook een beetje op mijn manier opgelost, omdat je weinig tijd had om te zeggen of het juist is of niet

ivm linting issues, ik kan de script niet runnen, enige dat ik visueel zie in vs code is te zien op foto. Die is absoluut hetzelfde als degene dat eronder staat, maar daar krijg ik geen melding van, dus ik begrijp niet waarom dit voorkomt.
![image](https://user-images.githubusercontent.com/54099103/131555496-7c67609c-27c1-4a3d-a23b-f4d553bd65db.png)

2021-08-31 22:39 UTC, erikap requested changes

2021-08-31 22:39 UTC, erikap commented on app/components/contact-item/modal.js
> +    }
Dit mag weg nu? Want je doet dit al in de `new.js` controller

2021-08-31 22:39 UTC, erikap commented on app/components/contact-item/modal.js
> +  @tracked contact;
Deze heb je niet meer nodig. Je kan overal `this.args.contact` gebruiken (en `@contact` in de template)

2021-08-31 22:39 UTC, erikap commented on app/controllers/contacts/new.js
> +  @tracked inputType = '';
Waarom hier een lege string? Kan gewoon `@tracked inputType;` zijn. Value wordt gezet in `setupController()` in de route.

2021-08-31 22:39 UTC, erikap commented on app/components/contact-item/modal.js
> +           isBlank(this.contact.mailAddress.get("value")) &&
Enkele quotes voor strings

2021-08-31 22:39 UTC, erikap commented on app/controllers/contacts/new.js
> +  @action
Newline toevoegen

2021-08-31 22:39 UTC, erikap commented on app/templates/contacts/new.hbs
> +      {{#if showContactItemModal}}
In de template moet je bij een variable altijd `this` of `@` gebruiken

2021-08-31 22:39 UTC, erikap commented on app/templates/contacts/new.hbs
> +          @onCancel={{this.closeContactItemModalAndReset}}
De rollback van de wijzigingen zou ik in de `modal.js` component uitvoeren, aangezien de wijzigingen daar ook toegepast worden. In `new.js` controller zou ik enkel nog het sluiten van de modal doen.

Het rollbacken is hier eenvoudiger dan bij persberichten/bronnen. Wanneer de gebruiker 'Annuleren' klikt, mogen wijzigingen sowieso ongedaan gemaakt worden. Er moet geen previous en huidige state vergeleken worden en er kunnen ook geen relaties wijzigen, dus de hele snapshot constructie is niet nodig. Je kan gewoon `rollbackAttributes` uitvoeren op alle modellen (het contact-item, de phone en het emailadres). Daarmee zouden alle wijzigingen ongedaan gemaakt moeten zijn.

2021-08-31 22:39 UTC, erikap commented on app/controllers/contacts/new.js
> +  }
Zie ook vorige comment. Deze constructie is hier niet nodig. De gewone `rollbackAttributes()` op de verschillende modellen moet volstaan.

2021-09-01 09:07 UTC, eduardtsatourov commented
ik heb bij contact-list modified toegevoegd, omdat we dit nodig gaan hebben voor pers-139, op de backend is er ook een branch pers-139 die dat toelaat

2021-09-01 09:10 UTC, eduardtsatourov commented
en hier is er geen resolve knop, maar is ook gefixt
![image](https://user-images.githubusercontent.com/54099103/131644776-69e08cbc-beac-45b0-b63b-4111f69c50ab.png)

2021-09-01 10:20 UTC, erikap approved these changes

2021-09-01 10:20 UTC, merged