adds contact adding function
kanselarij-vlaanderen/frontend-persberichten pull request #35
Opened 2021-09-07 10:40 UTC by eduardtsatourov

2021-09-07 21:25 UTC, erikap requested changes

2021-09-07 21:25 UTC, erikap commented on app/templates/contacts/overview.hbs
> +      </Auk::Button>
We kunnen deze knoppen best conditioneel maken op basis van de geselecteerd tab zodanig dat 'Verzendlijsten aanmaken' getoond wordt op de 'Verzendlijsten'-tab en 'Contactpersoon aanmaken' enkel bij 'Contactpersonen'-tab.

Je kan hiervoor de `router` service injecteren en gebruiken maken van de [`currentRoute` property](https://api.emberjs.com/ember/release/classes/RouterService/properties/currentRoute?anchor=currentRoute).

2021-09-08 11:33 UTC, eduardtsatourov commented
thanks voor de tip, ik dacht altijd dat ik in een parent geen toegang zou hebben wat er in een child geselecteerd werd

2021-09-09 09:43 UTC, Annelies-P approved these changes

2021-09-09 09:57 UTC, merged