Feature/pers 141
kanselarij-vlaanderen/frontend-persberichten pull request #36
Opened 2021-09-07 13:37 UTC by eduardtsatourov

2021-09-07 21:13 UTC, erikap requested changes

2021-09-07 21:13 UTC, erikap commented on app/controllers/contacts/mailing-list.js
> +      (await this.selectedContact.mailAddress).save()
Best checken of er `dirtyAttributes` zijn alvorens `save()` aan te roepen

2021-09-07 21:13 UTC, erikap commented on app/controllers/contacts/mailing-list.js
> +    contacts.removeObject(this.selectedContact);
Is dit noodzakelijk? Volgens mij wil je hier aan het einde van de method een refresh van het model doen (met de `reloadModel` route action zoals in een vorige comment)

2021-09-07 21:13 UTC, erikap commented on app/components/contact-item/sortable-table.hbs
> +<div class="auk-scroll-wrapper">
Kan deze component niet gemerged worden met `contact-item/table.hbs`? Het enige verschil lijkt mij de sortable table headers. Je kan bepalen adhv de `@onSortChange` action handler of de table sortable moet zijn: als het argument meegegeven wordt wel; anders niet.

2021-09-07 21:13 UTC, erikap commented on app/routes/contacts/mailing-list.js
> +    controller.selectedContact = null;
`controller.isEditEnabled` wil je hier ook resetten naar `false`

2021-09-07 21:13 UTC, erikap commented on app/controllers/contacts/new.js
> +    //zonder contact toe te voegen aan model en daarna nog eens model op te slagen, worden de contacten niet gelinked aan model
Dit is niet nodig omdat op hierboven `contact.contactList = this.model` al gedaan wordt en de relatie zo opgeslagen wordt.

2021-09-07 21:13 UTC, erikap commented on app/controllers/contacts/new.js
> +    const contactItems = yield this.model.contactItems;
Overbodig?

2021-09-07 21:18 UTC, erikap commented on app/templates/contacts/mailing-list.hbs
> +      <h1 class="auk-h1">Verzendlijsten</h1>
Dit moet de naam van de verzendlijst zijn

2021-09-09 08:41 UTC, Annelies-P approved these changes

2021-09-09 08:42 UTC, merged